---
- name: Create packer directory
  file: path=/opt/packer state=directory

- name: get packer binaries
  get_url: url=https://releases.hashicorp.com/packer/{{ packer_version }}/packer_{{ packer_version }}_linux_amd64.zip
           dest=/opt/packer/packer_{{ packer_version }}_linux_amd64.zip

- name: unzip packer
  unarchive: src=/opt/packer/packer_{{ packer_version }}_linux_amd64.zip
             dest=/opt/packer
             copy=no

- name: link packer to /usr/local/bin
  file: 
    src: '/opt/packer/packer'
    dest: '/usr/local/bin/packer'
    state: link
