---
- name: Create packer directory
  file:
    path: "{{ packer_basedir }}"
    state: directory

- name: Download and unzip packer 
  unarchive:
    src: https://releases.hashicorp.com/packer/{{ packer_version }}/packer_{{ packer_version }}_linux_amd64.zip
    dest: "{{ packer_basedir }}/"
    remote_src: True
    creates: "{{ packer_basedir }}/packer"

- name: Link packer to /usr/local/bin
  file: 
    src: "{{ packer_basedir }}/packer"
    dest: /usr/local/bin/packer
    state: link

- name: include OS templates
  import_tasks: OS_templates.yml
  when: packer_OS_templates
  tags: packer-templates

- name: include xauth
  import_tasks: xauth.yml
  when: packer_xauth
  tags: packer-xauth

- name: create OS images
  import_tasks: create_images.yml
  when: packer_create_images
  tags: packer-images
