---
- name: Create packer directory
  file:
    path: /opt/packer
    state: directory

- name: Download and unzip packer 
  unarchive:
    src: https://releases.hashicorp.com/packer/{{ packer_version }}/packer_{{ packer_version }}_linux_amd64.zip
    dest: /opt/packer/
    remote_src: True

- name: Link packer to /usr/local/bin
  file: 
    src: /opt/packer/packer
    dest: /usr/local/bin/packer
    state: link
