---
- name: Create packer directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ packer_basedir }}/buildDir"
    - "{{ packer_basedir }}/distros/centos7/docroot"

- name: generate centOS7 ks file
  template:
    src: distros/centos7/centos7-base.json.j2
    dest: "{{ packer_basedir }}/distros/centos7/centos7-base.json"

- name: generate centOS7 ks file
  template:
    src: distros/centos7/docroot/c7-kvm-ks.cfg.j2
    dest: "{{ packer_basedir }}/distros/centos7/docroot/c7-kvm-ks.cfg"

- name: generate provisioner
  template:
    src: distros/centos7/provision.sh.j2
    dest: "{{ packer_basedir }}/distros/centos7/provision.sh"
    owner: root
    mode: 0755
