---

- name: install xauth
  package:
    name: xauth
    state: latest

- name: set X11Forwarding to yes
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^X11Forwarding\s'
    line: 'X11Forwarding yes'
  register: sshd_config_X11Forwarding

- name: set X11UseLocalhost to no
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^X11UseLocalhost\s'
    line: 'X11UseLocalhost no'
  register: sshd_config_X11UseLocalhost 

- name: restart sshd
  service:
    name: sshd
    state: restarted
  when: sshd_config_X11Forwarding.changed or sshd_config_X11UseLocalhost.changed
